# Input directories
r1_dir: "tests_outs/benchmarking/regenerated"
r2_dir: "tests_outs/benchmarking/regenerated"
output_dir: "tests_outs/benchmarking/regenerated_reports"

# Run names
run_config: [
  {
    "run_name": "metauto-dl",
    "type": "metauto",
    "db_path": "models/model.pt",
    "extra": "metauto",
    "threads": 16
  },
  {
    "run_name": "centrifuge-run",
    "type": "centrifuge",
    "db_path": "db/centrifuge/custom_idx",
    "extra": "centrifuge",
    "threads": 16
  },
  {
    "run_name": "assembly-pipeline",
    "type": "assembly_hybrid",
    "db_path": "db/kraken2",
    "extra": "assembly_hybrid",
    "threads": 16
  }
]
