# Python package (install.sh)

name: Python package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12"]

    steps:
    - uses: actions/checkout@v4
    - uses: conda-incubator/setup-miniconda@v3
      with:
        python-version: ${{ matrix.python-version }}
        auto-update-conda: true
        activate-environment: samovar
        environment-file: environment.yml
    - name: Install via install.sh
      env:
        CI: "true"
        NCBI_EMAIL: test@samovar.com
        SAMOVAR_INSTALL_DEV: "1"
        SAMOVAR_UPDATE_SHELL: "0"
      run: |
        chmod +x install.sh
        ./install.sh
    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pytest -q --tb=short --cov=src
